### PR TITLE
Some Minor Tweaks

### PR DESCRIPTION
**Pull request by GrahamCampbell**
The function visibility thing is a PSR thing btw, and I am aware you are not following PSR, but I think it's nice to have that consistency with the function visibility anyway.

### CODE REVIEW

**Comment by nazar-pc** [comment]
I do not prefer explicit declaration of `public` visibility.
Also, `transform` method should not be protected, because it is used for non-static calls.
Protected visibility to `doFencedFigures` I've just added separately.

BTW, I've started some work on [Alternative PSR's](https://github.com/nazar-pc/cs-standards), I'm planning to add new APSR every few days, also additional files will be added with explanations why every APSR differs from PSR for easy clarifying differences and intentions, hopefully, someone will consider that thoughts sensible.

**Comment by GrahamCampbell** [comment]
Sure. Is there any chance you could tag a 2.0.4 release for the current state?

**Comment by nazar-pc** [comment]
https://github.com/nazar-pc/php-markdown-next/releases/tag/2.0.4

**Comment by GrahamCampbell** [comment]
Thanks. Also, just so you know - https://github.com/GrahamCampbell/Laravel-Markdown/commit/dfff9d0b3ae2300f1f8aed6d56ffa8dcb55a7864. I've merged that branch into develop now, so my wrapper package will be using this repo from the next release for definate.

**Comment by nazar-pc** [comment]
I'm happy to hear this)

**Pull request closed without merging**
